name: Build Monte Card APK

on:
  push:
    branches: [ android-build ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk build-essential git unzip zip wget curl
        
    - name: Set up Android SDK
      uses: android-actions/setup-android@v4
      with:
        api-level: 33
        build-tools-version: 33.0.0
        ndk-version: 25.2.9519653
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 pillow
        
    - name: Set environment variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
        
    - name: Symlink build-tools for Buildozer
      run: |
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk
        ln -sfn $ANDROID_SDK_ROOT/build-tools /home/runner/.buildozer/android/platform/android-sdk/build-tools
        
    - name: Symlink cmdline-tools for Buildozer compatibility
      run: |
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk
        ln -sfn $ANDROID_SDK_ROOT/cmdline-tools/latest /home/runner/.buildozer/android/platform/android-sdk/tools
        
    - name: Verify SDK paths
      run: |
        echo "=== Android SDK Structure ==="
        ls -la $ANDROID_SDK_ROOT/ || echo "SDK root not found"
        echo "=== Buildozer Expected Paths ==="
        ls -la /home/runner/.buildozer/android/platform/android-sdk/ || echo "Buildozer paths not created yet"
        echo "=== SDK Manager Location ==="
        find $ANDROID_SDK_ROOT -name "sdkmanager" -type f || echo "sdkmanager not found"
        
    - name: Create app icon
      run: |
        mkdir -p data
        python3 -c "from PIL import Image, ImageDraw; img = Image.new('RGB', (512, 512), (33, 150, 243)); draw = ImageDraw.Draw(img); draw.rectangle([100, 100, 412, 412], fill=(255, 255, 255)); img.save('data/icon.png'); print('Icon created')"
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-
          
    - name: Build APK
      run: |
        yes | buildozer android debug
        
    - name: List build output
      run: |
        echo "=== Build completed ==="
        ls -la bin/ || echo "No bin directory"
        find . -name "*.apk" -type f || echo "No APK found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: monte-card-apk
        path: bin/*.apk
        retention-days: 30
