name: Test Build

on:
  push:
    branches: [ android-build ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: List files
      run: ls -la