name: Build Monte Card APK
on:
  push:
    branches: [ android-build ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk build-essential git unzip zip wget curl
        
    - name: Set up Android SDK manually
      run: |
        # Create Android SDK directory
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        
        # Download and install command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true
        
        # Set environment variables
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Accept licenses and install required packages
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0"
        sdkmanager "ndk;25.2.9519653"
        
    - name: Set environment variables
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 pillow
        
    - name: Setup Buildozer directories
      run: |
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk
        ln -sfn $ANDROID_SDK_ROOT/build-tools /home/runner/.buildozer/android/platform/android-sdk/build-tools
        ln -sfn $ANDROID_SDK_ROOT/cmdline-tools/latest /home/runner/.buildozer/android/platform/android-sdk/tools
        ln -sfn $ANDROID_SDK_ROOT/platforms /home/runner/.buildozer/android/platform/android-sdk/platforms
        ln -sfn $ANDROID_SDK_ROOT/platform-tools /home/runner/.buildozer/android/platform/android-sdk/platform-tools
        
    - name: Verify SDK setup
      run: |
        echo "=== Environment Variables ==="
        echo "ANDROID_HOME: $ANDROID_HOME"
        echo "ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"
        echo "JAVA_HOME: $JAVA_HOME"
        echo "=== SDK Structure ==="
        ls -la $ANDROID_SDK_ROOT/ || echo "SDK root not found"
        echo "=== SDK Manager ==="
        which sdkmanager || echo "sdkmanager not in PATH"
        sdkmanager --list_installed || echo "Could not list installed packages"
        
    - name: Create app icon
      run: |
        mkdir -p data
        python3 -c "
from PIL import Image, ImageDraw
img = Image.new('RGB', (512, 512), (33, 150, 243))
draw = ImageDraw.Draw(img)
draw.rectangle([100, 100, 412, 412], fill=(255, 255, 255))
img.save('data/icon.png')
print('Icon created successfully')
        "
        
    - name: Cache buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}
        
    - name: Cache buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-
          
    - name: Build APK
      run: |
        # Ensure environment is properly set for buildozer
        export ANDROID_HOME=$HOME/android-sdk
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export ANDROID_NDK_ROOT=$HOME/android-sdk/ndk/25.2.9519653
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools
        
        # Build with buildozer
        yes | buildozer android debug
        
    - name: List build output
      run: |
        echo "=== Build completed ==="
        ls -la bin/ || echo "No bin directory found"
        find . -name "*.apk" -type f || echo "No APK files found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: monte-card-apk
        path: bin/*.apk
        retention-days: 30
