name: Build Desktop Apps

on:
  push:
    branches: [ main, kivymd-ui-update-direct ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libegl1-mesa libgles2-mesa libgbm1 python3-dev
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller kivy kivymd pillow requests qrcode bcrypt cryptography pygame plyer
        
    - name: Build Linux executable
      run: |
        export KIVY_WINDOW=sdl2
        export KIVY_GL_BACKEND=gl
        export SDL_VIDEODRIVER=dummy
        export DISPLAY=:99
        
        Xvfb :99 -screen 0 1024x768x24 &
        sleep 3
        
        pyinstaller --onedir --windowed \
          --name "AceVault-Linux" \
          --hidden-import kivymd \
          --hidden-import kivymd.uix \
          --hidden-import plyer \
          --hidden-import plyer.platforms \
          --hidden-import cryptography \
          --hidden-import bcrypt \
          --hidden-import pygame \
          --hidden-import qrcode \
          --hidden-import requests \
          --hidden-import PIL \
          main.py
          
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: acevault-linux
        path: dist/AceVault-Linux/

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller kivy kivymd pillow requests qrcode bcrypt cryptography pygame plyer
        
    - name: Build macOS executable
      run: |
        pyinstaller --onedir --windowed \
          --name "AceVault-macOS" \
          --hidden-import kivymd \
          --hidden-import kivymd.uix \
          --hidden-import plyer \
          --hidden-import plyer.platforms \
          --hidden-import cryptography \
          --hidden-import bcrypt \
          --hidden-import pygame \
          --hidden-import qrcode \
          --hidden-import requests \
          --hidden-import PIL \
          main.py
          
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: acevault-macos
        path: dist/AceVault-macOS/
