name: Build Windows Executable

on:
  push:
    branches: [ kivymd-ui-update-direct, clean-kivymd-ui-update ]
  pull_request:
    branches: [ kivymd-ui-update-direct, clean-kivymd-ui-update ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka kivymd kivy pillow requests qrcode bcrypt cryptography pygame plyer
        
    - name: Build Windows executable
      run: |
        nuitka --standalone --include-package=kivymd --include-package=kivy --include-package=PIL --include-package=requests --include-package=qrcode --include-package=bcrypt --include-package=cryptography --include-package=pygame --include-package=plyer --windows-disable-console --output-filename=AceVault-Windows.exe --assume-yes-for-downloads main.py
        
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: AceVault-Windows-Executable
        path: main.dist/
        retention-days: 30
