name: Build Desktop Apps

on:
  push:
    branches: [ main, kivymd-ui-update-direct ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller kivy kivymd pillow requests qrcode bcrypt cryptography pygame plyer
        
    - name: Build Windows executable
      run: |
        pyinstaller --onedir --windowed --name "AceVault-Windows" --hidden-import kivymd --hidden-import kivymd.uix --hidden-import kivymd.icon_definitions --hidden-import kivymd.icon_definitions.md_icons --hidden-import kivymd.font_definitions --hidden-import kivymd.material_resources --hidden-import kivymd.uix.boxlayout --hidden-import kivymd.uix.label --hidden-import kivymd.uix.button --hidden-import kivymd.uix.card --hidden-import kivymd.uix.gridlayout --hidden-import kivymd.uix.scrollview --hidden-import plyer --hidden-import plyer.platforms --hidden-import cryptography --hidden-import bcrypt --hidden-import pygame --hidden-import qrcode --hidden-import requests --hidden-import PIL main.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: acevault-windows
        path: dist/AceVault-Windows/