name: Build Desktop Apps

on:
  push:
    branches: [ main, kivymd-ui-update-direct ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller kivy kivymd pillow requests qrcode bcrypt cryptography pygame plyer
        
    - name: Set Kivy environment variables globally
      run: |
        echo "KIVY_NO_CONSOLELOG=1" >> $env:GITHUB_ENV
        echo "KIVY_WINDOW=dummy" >> $env:GITHUB_ENV
        echo "KIVY_GL_BACKEND=mock" >> $env:GITHUB_ENV
        echo "KIVY_NO_ARGS=1" >> $env:GITHUB_ENV
        echo "KIVY_NO_WINDOW=1" >> $env:GITHUB_ENV
        
    - name: Build Windows executable (simple approach)
      run: |
        pyinstaller --onefile --windowed --name "AceVault-Windows" --hidden-import kivymd --hidden-import kivymd.uix --hidden-import kivymd.icon_definitions --hidden-import kivymd.font_definitions --hidden-import kivymd.material_resources --hidden-import plyer --hidden-import plyer.platforms --hidden-import cryptography --hidden-import bcrypt --hidden-import pygame --hidden-import qrcode --hidden-import requests --hidden-import PIL main.py
        
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: acevault-windows
        path: dist/AceVault-Windows.exe