name: Build Cross-Platform Executables

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libffi-dev libssl-dev
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install kivy kivymd pillow requests qrcode pygame bcrypt plyer cryptography pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --name "AceVault-Linux" \
          --hidden-import kivymd \
          --hidden-import kivymd.uix \
          --hidden-import plyer \
          --hidden-import plyer.platforms \
          --hidden-import cryptography \
          --hidden-import bcrypt \
          --hidden-import pygame \
          --hidden-import qrcode \
          --hidden-import requests \
          --hidden-import PIL \
          --collect-submodules plyer \
          --collect-submodules kivymd \
          main.py
    
    - name: Upload Linux Executable
      uses: actions/upload-artifact@v4
      with:
        name: AceVault-Linux
        path: dist/AceVault-Linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install kivy kivymd pillow requests qrcode pygame bcrypt plyer cryptography pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name "AceVault-Windows" --hidden-import kivymd --hidden-import kivymd.uix --hidden-import plyer --hidden-import plyer.platforms --hidden-import cryptography --hidden-import bcrypt --hidden-import pygame --hidden-import qrcode --hidden-import requests --hidden-import PIL --collect-submodules plyer --collect-submodules kivymd main.py
    
    - name: Upload Windows Executable
      uses: actions/upload-artifact@v4
      with:
        name: AceVault-Windows
        path: dist/AceVault-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install kivy kivymd pillow requests qrcode pygame bcrypt plyer cryptography pyinstaller
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed \
          --name "AceVault-macOS" \
          --hidden-import kivymd \
          --hidden-import kivymd.uix \
          --hidden-import plyer \
          --hidden-import plyer.platforms \
          --hidden-import cryptography \
          --hidden-import bcrypt \
          --hidden-import pygame \
          --hidden-import qrcode \
          --hidden-import requests \
          --hidden-import PIL \
          --collect-submodules plyer \
          --collect-submodules kivymd \
          main.py
    
    - name: Upload macOS Executable
      uses: actions/upload-artifact@v4
      with:
        name: AceVault-macOS
        path: dist/AceVault-macOS
