name: Build Monte Card APK
on:
  push:
    branches: [ android-build ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk build-essential git unzip zip
        
    - name: Setup Android SDK
      run: |
        # Download and install Android SDK command line tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        
        # Set environment variables
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH
        
    - name: Install Android SDK components
      run: |
        # Accept licenses and install required components
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
        
    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33 pillow
        
    - name: Set Java environment
      run: |
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        
    - name: Create app icon
      run: |
        mkdir -p data
        python3 -c "from PIL import Image, ImageDraw; img = Image.new('RGB', (512, 512), (33, 150, 243)); draw = ImageDraw.Draw(img); draw.rectangle([100, 100, 412, 412], fill=(255, 255, 255)); img.save('data/icon.png'); print('Icon created')"
        
    - name: Verify aidl installation
      run: |
        which aidl || echo "aidl not in PATH"
        ls -la $HOME/android-sdk/build-tools/33.0.2/ | grep aidl || echo "aidl not found in build-tools"
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: List build output
      run: |
        echo "=== Build completed ==="
        ls -la bin/ || echo "No bin directory"
        find . -name "*.apk" -type f || echo "No APK found"
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: monte-card-apk
        path: bin/*.apk
