name: Build Monte Card Windows EXE

on:
  push:
    branches: [ imports-removed ]
  pull_request:
    branches: [ imports-removed ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka kivymd kivy pillow pygame==2.1.3 qrcode requests mutagen imageio cryptography bcrypt
        
    - name: Build Windows executable
      run: |
        python -m nuitka --standalone ^
          --include-package=kivymd ^
          --include-package=kivy ^
          --include-package=PIL ^
          --include-package=requests ^
          --include-package=qrcode ^
          --include-package=bcrypt ^
          --include-package=cryptography ^
          --include-package=pygame ^
          --include-package=mutagen ^
          --include-package=imageio ^
          --windows-disable-console ^
          --output-filename=MonteCard-Windows.exe ^
          --assume-yes-for-downloads ^
          main.py
          
    - name: Upload Windows executable
      uses: actions/upload-artifact@v4
      with:
        name: MonteCard-Windows-EXE-${{ github.sha }}
        path: main.dist/
        retention-days: 30
