name: Build Windows Executable

on:
  push:
    branches: [ android-removed ]
  pull_request:
    branches: [ android-removed ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install kivymd
          pip install kivy
          pip install pillow
          pip install requests
          pip install qrcode
          pip install bcrypt
          pip install cryptography
          pip install pygame
          pip install plyer
          pip install opencv-python
          pip install openpyxl
          pip install docx2txt
          pip install mutagen
          pip install imageio
          pip install imageio_ffmpeg
          pip install psutil

      - name: Download and setup UPX
        run: |
          $upx_version = "4.2.1" # Check for the latest UPX version on GitHub releases
          $upx_zip = "upx-$upx_version-win64.zip"
          $upx_url = "https://github.com/upx/upx/releases/download/v$upx_version/$upx_zip"
          Write-Host "Downloading UPX from $upx_url"
          Invoke-WebRequest -Uri $upx_url -OutFile $upx_zip
          Expand-Archive -Path $upx_zip -DestinationPath . -Force
          # Find the actual extracted folder name (e.g., upx-4.2.1-win64)
          $upx_folder = (Get-ChildItem -Path . -Directory | Where-Object {$_.Name -like "upx-*-win64"}).Name
          Write-Host "UPX extracted to folder: $upx_folder"
          # Add UPX to PATH for this step or reference it directly
          $env:Path += ";$pwd\$upx_folder"
          upx --version # Verify UPX is working

      - name: Build Windows executable
        run: |
          python -m nuitka --standalone `
          --lto=yes `
          --verbose `             # Enable general Nuitka verbosity
          --show-modules `        # Show a summary of included modules
          --show-memory `         # Show memory usage statistics
          --windows-disable-console `
          --assume-yes-for-downloads `
          --plugin-enable=upx `   # Enable UPX plugin
          --upx-binary=upx.exe `  # Tell Nuitka to use 'upx.exe' from PATH (set above)
          --output-filename=AceInTheHole-Windows.exe `
          --include-package=kivymd `
          --include-package=kivy `
          --include-package=PIL `
          --include-package=requests `
          --include-package=qrcode `
          --include-package=bcrypt `
          --include-package=cryptography `
          --include-package=pygame `
          --include-package=plyer `
          --include-package=opencv-python `
          --include-package=openpyxl `
          --include-package=docx2txt `
          --include-package=mutagen `
          --include-package=imageio `
          --include-package=psutil `
          main.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: AceInTheHole-Windows-Executable
          path: main.dist/
          retention-days: 30

      - name: Create release info
        run: |
          echo "Build completed successfully!" > build-info.txt
          echo "Download the AceInTheHole-Windows-Executable artifact" >> build-info.txt
          echo "Extract and run AceInTheHole-Windows.exe" >> build-info.txt

      - name: Upload build info
        uses: actions/upload-artifact@v4
        with:
          name: Build-Instructions
          path: build-info.txt
